#version: "3"
services:
  pacs-server:
    container_name: pacs-server
    image: jodogne/orthanc-plugins:1.12.11
    ports:
      - {{DICOM_PORT}}:{{DICOM_PORT}}
      - {{HTTP_PORT}}:{{HTTP_PORT}}
    volumes:
      - ./pacs-server.json:/etc/orthanc/orthanc.json:ro
      - ./lua:/etc/orthanc/lua:ro
      - ./data:/var/lib/orthanc/db/
    restart: always
    networks:
      - {{NETWORK_NAME}}

  pacs-viewer:
    container_name: pacs-viewer
    image: ohif/viewer
    ports:
      - {{VIEWER_PORT}}:80
    environment:
      - APP_CONFIG=/usr/share/nginx/html/app-config.js
    volumes:
      - ./nginx_viewer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./viewer.js:/usr/share/nginx/html/app-config.js:ro
      - ./manifest.json:/usr/share/nginx/html/manifest.json:ro
      - ./assets/custom.css:/usr/share/nginx/html/custom.css:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets/favicon.svg:/usr/share/nginx/html/favicon.svg:ro
      - ./assets/Hospital-Labuan.jpg:/usr/share/nginx/html/Hospital-Labuan.jpg:ro
    restart: always
    networks:
      - {{NETWORK_NAME}}

networks:
  {{NETWORK_NAME}}:
    external: true
